### ISSUE TITLE
AWS-Bridge connection

### ISSUE THREAD

**Issue by NagarjunaReddy1242** [awslabs/mqtt-kinesis-bridge#4]
same way i have to install every thing once it is completed than i did run but i got error
error is : 
**Starting MQTT-to-Kinesis bridge
Bridge Connected, looping...
Traceback (most recent call last):
  File "bridge.py", line 140, in <module>
    bridge.client.loop_forever()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1469, in loop_forever
    self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 895, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.gaierror: [Errno -5] No address associated with hostname**

can you please solve my problem
![bridgeconnection](https://user-images.githubusercontent.com/24729276/36829515-81626baa-1d45-11e8-858e-1c49e4442915.JPG)

**Comment by brettf** [comment]
This looks like you did not run the local `mosquitto` broker.
